server:
  port: 0
turnkey:
  app:
    base-path: /api/quotations
    v1:
      context-path: ${turnkey.app.base-path}/v1
    v2:
      context-path: ${turnkey.app.base-path}/v2
spring:
  application:
    name: quotations-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://turnquest-discovery-service:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true